security:
  jwt:
    secret-key: "ksadjfioajisbdfauhsvfavsfgasvfgafc6rhasvfgyasf"
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://pap-database:5432/pap