spring:
  profiles:
    default: "dev"
  data:
    rest:
      base-path: "/api"
  mail:
    username: "mg.puppet@gmail.com"
    host: "smtp.gmail.com"
    port: "587"
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
server:
  forward-headers-strategy: framework
app:
  confirm-email-url: "/user/verify/"
  reset-password-url: "/user/reset-password/"