security:
  jwt:
    secret-key: "dupa"
email-verification:
  confirm-base-url: "http://localhost:3000/user/verify/"
  reset-password-base-url: "http://localhost:3000/user/reset-password/"
app:
  website-base-url: "http://localhost:3000"