name: Build and publish Frontend app

on:
  workflow_call:

jobs:
  docker-build-publish-frontend:
    name: Build and publish docker image of frontend app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - run: cd frontend
      - run: npm install
      - run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: mgarbowski/pap-projekt-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mgarbowski/pap-projekt-frontend:latest
          labels: ${{ steps.meta.outputs.labels }}